all:block_wait exec myenv path zombie create_pro exit noblock_wait vfork environ getenv orphan_proc wait get_status
get_status:get_status.c
	gcc $^ -o $@
block_wait:block_wait.c
	gcc $^ -o $@
exec:exec.c
	gcc $^ -o $@
myenv:myenv.c   
	gcc $^ -o $@
path:path.c
	gcc $^ -o $@
zombie:zombie.c
	gcc $^ -o $@
create_pro:create_pro.c
	gcc $^ -o $@
exit:exit.c
	gcc $^ -o $@
noblock_wait:noblock_wait.c
	gcc $^ -o $@
vfork:vfork.c
	gcc $^ -o $@
environ:environ.c
	gcc $^ -o $@
getenv:getenv.c
	gcc $^ -o $@
orphan_proc:orphan_proc.c
	gcc $^ -o $@
wait:wait.c
	gcc $^ -o $@
